[database]
    [database.mysql]
        [database.mysql.default]
            host = '127.0.0.1'
            port = 3306
            user = 'root'
            password = ''
            db = 'douyin'
            max_connections = 10  # 最大链接数
            is_async = 0  # 是否异步（默认同步）
        [database.mysql.dawn]
            host = '127.0.0.1'
            port = 3306
            user = 'root'
            password = '123456'
            db = 'dawn'
            max_connections = 10
            is_async = 1
    [database.redis]
        [database.redis.default]
            host = '127.0.0.1'
            port = 6379
            db = 1
            maxsize = 10
# 日志配置
[logger]
    [logger.root]
        filename = '/Users/zhangzhiliang/data0/logs/root.log'
        maxBytes = 1024100 # 文件大小为100M
        backupCount = 5 # 备份份数
    [logger.other]
        filename = '/Users/zhangzhiliang/data0/logs/other.log'
        maxBytes = 1024100 # 文件大小为100M
        backupCount = 5 # 备份份数