[database]
    [database.mysql]
        [database.mysql.default]
            host = '127.0.0.1'
            port = 3306
            user = 'root'
            password = ''
            db = 'douyin'
            max_connections = 10  # 最大链接数
            is_async = 0  # 是否异步（默认同步）
        [database.mysql.dawn]
            host = '127.0.0.1'
            port = 3306
            user = 'root'
            password = '123456'
            db = 'dawn'
            max_connections = 10
            is_async = 1
    [database.redis]
        [database.redis.default]
            host = '127.0.0.1'
            port = 6379
            db = 1
            password = ''